# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0003_auto_20171126_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='oc_server.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='oc_server.Course'),
        ),
    ]
