# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0008_draggabletextfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='draggabletextfield',
            name='lineNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draggabletextfield',
            name='draggable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textFields', to='oc_server.Draggable'),
        ),
    ]
