# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0010_baseprofile_current_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggable',
            name='descName',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='draggabletextfield',
            name='placeholderText',
            field=models.CharField(max_length=32),
        ),
    ]
