# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0011_auto_20180129_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggable',
            name='descName',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
