# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0012_baseprofile_completed_section_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofile',
            name='current_section',
        ),
    ]
