# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0011_feedbacksubmission'),
        ('oc_server', '0012_auto_20180129_0043'),
    ]

    operations = [
    ]
