# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0014_feedbacksubmission_date'),
        ('oc_server', '0013_remove_baseprofile_current_section'),
    ]

    operations = [
    ]
