version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'ocdev'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis
  celery:
    build:
      context: .
      dockerfile: ./Dockerfile-Celery
    command: celery -A oc_backend -l info -b "redis://redis:6379" worker
    user: celery
    network_mode: "host"
    environment:
      DOCKER_HOST: "tcp://localhost:2375"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock