FROM python:3

RUN mkdir /oc_backend/
WORKDIR /oc_backend/
COPY requirements.txt .

RUN pip install -r requirements.txt

COPY oc_backend/celery.py oc_backend/settings.py oc_backend/__init__.py ./oc_backend/
COPY oc_api/pyexec ./oc_api/pyexec

ENV APP_USER celery
ENV APP_ROOT /src

RUN groupadd -r ${APP_USER} \
    && useradd -r -m \
    --home-dir ${APP_ROOT} \
    -s /usr/sbin/nologin \
    -g ${APP_USER} ${APP_USER}

USER ${APP_USER}