# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sections',
        ),
    ]
