# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0002_auto_20171126_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oc_server.Course'),
        ),
        migrations.AddField(
            model_name='section',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oc_server.Lesson'),
        ),
    ]
