# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0005_draggable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('unitTests', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='oc_server.Section')),
            ],
        ),
    ]
