# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0007_baseprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraggableTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startChar', models.PositiveIntegerField()),
                ('endChar', models.PositiveIntegerField()),
                ('placeholderText', models.CharField(max_length=24)),
                ('draggable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textField', to='oc_server.Draggable')),
            ],
        ),
    ]
