# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_server', '0013_merge_20180206_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 3, 13, 10, 608622)),
            preserve_default=False,
        ),
    ]
